// Generated by Nuxt'
import type { Plugin } from '#app'

type Decorate<T extends Record<string, any>> = { [K in keyof T as K extends string ? `$${K}` : never]: T[K] }

type InjectionType<A extends Plugin> = A extends {default: Plugin<infer T>} ? Decorate<T> : unknown

type NuxtAppInjections = 
  InjectionType<typeof import("../../node_modules/.pnpm/nuxt@3.20.1_@parcel+watcher@2.5.1_@types+node@24.10.1_@vue+compiler-sfc@3.5.24_db0@0.3._b5c6af8f109483f88e7516349693bf5a/node_modules/nuxt/dist/app/plugins/revive-payload.client.js")> &
  InjectionType<typeof import("../../node_modules/.pnpm/nuxt-site-config@3.2.11_h3@1.15.4_magicast@0.5.1_vue@3.5.24_typescript@5.9.3_/node_modules/nuxt-site-config/dist/runtime/app/plugins/0.siteConfig.js")> &
  InjectionType<typeof import("../../node_modules/.pnpm/nuxt@3.20.1_@parcel+watcher@2.5.1_@types+node@24.10.1_@vue+compiler-sfc@3.5.24_db0@0.3._b5c6af8f109483f88e7516349693bf5a/node_modules/nuxt/dist/head/runtime/plugins/unhead.js")> &
  InjectionType<typeof import("../../node_modules/.pnpm/nuxt@3.20.1_@parcel+watcher@2.5.1_@types+node@24.10.1_@vue+compiler-sfc@3.5.24_db0@0.3._b5c6af8f109483f88e7516349693bf5a/node_modules/nuxt/dist/pages/runtime/plugins/router.js")> &
  InjectionType<typeof import("../../node_modules/.pnpm/nuxt@3.20.1_@parcel+watcher@2.5.1_@types+node@24.10.1_@vue+compiler-sfc@3.5.24_db0@0.3._b5c6af8f109483f88e7516349693bf5a/node_modules/nuxt/dist/app/plugins/browser-devtools-timing.client.js")> &
  InjectionType<typeof import("../../node_modules/.pnpm/nuxt@3.20.1_@parcel+watcher@2.5.1_@types+node@24.10.1_@vue+compiler-sfc@3.5.24_db0@0.3._b5c6af8f109483f88e7516349693bf5a/node_modules/nuxt/dist/app/plugins/dev-server-logs.js")> &
  InjectionType<typeof import("../../node_modules/.pnpm/nuxt@3.20.1_@parcel+watcher@2.5.1_@types+node@24.10.1_@vue+compiler-sfc@3.5.24_db0@0.3._b5c6af8f109483f88e7516349693bf5a/node_modules/nuxt/dist/app/plugins/navigation-repaint.client.js")> &
  InjectionType<typeof import("../../node_modules/.pnpm/nuxt@3.20.1_@parcel+watcher@2.5.1_@types+node@24.10.1_@vue+compiler-sfc@3.5.24_db0@0.3._b5c6af8f109483f88e7516349693bf5a/node_modules/nuxt/dist/app/plugins/check-outdated-build.client.js")> &
  InjectionType<typeof import("../../node_modules/.pnpm/nuxt@3.20.1_@parcel+watcher@2.5.1_@types+node@24.10.1_@vue+compiler-sfc@3.5.24_db0@0.3._b5c6af8f109483f88e7516349693bf5a/node_modules/nuxt/dist/app/plugins/revive-payload.server.js")> &
  InjectionType<typeof import("../../node_modules/.pnpm/nuxt@3.20.1_@parcel+watcher@2.5.1_@types+node@24.10.1_@vue+compiler-sfc@3.5.24_db0@0.3._b5c6af8f109483f88e7516349693bf5a/node_modules/nuxt/dist/app/plugins/chunk-reload.client.js")> &
  InjectionType<typeof import("../../node_modules/.pnpm/nuxt-seo-utils@7.0.18_h3@1.15.4_magicast@0.5.1_rollup@4.53.2_vue@3.5.24_typescript@5.9.3_/node_modules/nuxt-seo-utils/dist/runtime/app/plugins/siteConfig.js")> &
  InjectionType<typeof import("../../node_modules/.pnpm/nuxt-seo-utils@7.0.18_h3@1.15.4_magicast@0.5.1_rollup@4.53.2_vue@3.5.24_typescript@5.9.3_/node_modules/nuxt-seo-utils/dist/runtime/app/plugins/inferSeoMetaPlugin.js")> &
  InjectionType<typeof import("../../node_modules/.pnpm/nuxt-seo-utils@7.0.18_h3@1.15.4_magicast@0.5.1_rollup@4.53.2_vue@3.5.24_typescript@5.9.3_/node_modules/nuxt-seo-utils/dist/runtime/app/plugins/titles.js")> &
  InjectionType<typeof import("../../node_modules/.pnpm/nuxt-schema-org@5.0.9_@unhead+vue@2.0.19_vue@3.5.24_typescript@5.9.3___h3@1.15.4_magica_41b060ef88436e380c94f1795829b7d5/node_modules/nuxt-schema-org/dist/runtime/app/plugins/defaults.js")> &
  InjectionType<typeof import("../../node_modules/.pnpm/nuxt-schema-org@5.0.9_@unhead+vue@2.0.19_vue@3.5.24_typescript@5.9.3___h3@1.15.4_magica_41b060ef88436e380c94f1795829b7d5/node_modules/nuxt-schema-org/dist/runtime/app/plugins/init.js")> &
  InjectionType<typeof import("../../node_modules/.pnpm/nuxt-og-image@5.1.12_@unhead+vue@2.0.19_vue@3.5.24_typescript@5.9.3___h3@1.15.4_magicas_ca512f5576cf437f35995b3adf825a2b/node_modules/nuxt-og-image/dist/runtime/app/plugins/og-image-canonical-urls.server.js")> &
  InjectionType<typeof import("../../node_modules/.pnpm/nuxt-og-image@5.1.12_@unhead+vue@2.0.19_vue@3.5.24_typescript@5.9.3___h3@1.15.4_magicas_ca512f5576cf437f35995b3adf825a2b/node_modules/nuxt-og-image/dist/runtime/app/plugins/route-rule-og-image.server.js")> &
  InjectionType<typeof import("../../node_modules/.pnpm/nuxt-link-checker@4.3.6_db0@0.3.4_h3@1.15.4_ioredis@5.8.2_magicast@0.5.1_vite@7.2.2_@ty_6a1af5f5dcbb3850ec05a068cd3039a6/node_modules/nuxt-link-checker/dist/runtime/app/plugins/ui.client.js")> &
  InjectionType<typeof import("../../node_modules/.pnpm/@nuxtjs+robots@5.5.6_h3@1.15.4_magicast@0.5.1_vue@3.5.24_typescript@5.9.3_/node_modules/@nuxtjs/robots/dist/runtime/app/plugins/robot-meta.server.js")> &
  InjectionType<typeof import("../../node_modules/.pnpm/nuxt@3.20.1_@parcel+watcher@2.5.1_@types+node@24.10.1_@vue+compiler-sfc@3.5.24_db0@0.3._b5c6af8f109483f88e7516349693bf5a/node_modules/nuxt/dist/pages/runtime/plugins/prefetch.client.js")> &
  InjectionType<typeof import("../../node_modules/.pnpm/nuxt@3.20.1_@parcel+watcher@2.5.1_@types+node@24.10.1_@vue+compiler-sfc@3.5.24_db0@0.3._b5c6af8f109483f88e7516349693bf5a/node_modules/nuxt/dist/pages/runtime/plugins/check-if-page-unused.js")> &
  InjectionType<typeof import("../../node_modules/.pnpm/@nuxt+devtools@1.0.5_encoding@0.1.13_nuxt@3.20.1_@parcel+watcher@2.5.1_@types+node@24.1_5fb832555de8cb2b9a46a4cbd700a527/node_modules/@nuxt/devtools/dist/runtime/plugins/devtools.server.js")> &
  InjectionType<typeof import("../../node_modules/.pnpm/@nuxt+devtools@1.0.5_encoding@0.1.13_nuxt@3.20.1_@parcel+watcher@2.5.1_@types+node@24.1_5fb832555de8cb2b9a46a4cbd700a527/node_modules/@nuxt/devtools/dist/runtime/plugins/devtools.client.js")> &
  InjectionType<typeof import("../../node_modules/.pnpm/@nuxt+content@2.13.4_db0@0.3.4_ioredis@5.8.2_magicast@0.5.1_nuxt@3.20.1_@parcel+watcher_e2feb6ea5c5477d87ea0e59a738c297d/node_modules/@nuxt/content/dist/runtime/plugins/ws.js")> &
  InjectionType<typeof import("../../node_modules/.pnpm/@nuxt+ui@2.11.1_magicast@0.5.1_vite@7.2.2_@types+node@24.10.1_jiti@2.6.1_lightningcss@1_d5b464d7c9a9fb60c4224c8539aeccd0/node_modules/@nuxt/ui/dist/runtime/plugins/colors.js")> &
  InjectionType<typeof import("../../node_modules/.pnpm/@nuxtjs+color-mode@3.5.2_magicast@0.5.1/node_modules/@nuxtjs/color-mode/dist/runtime/plugin.server.js")> &
  InjectionType<typeof import("../../node_modules/.pnpm/@nuxtjs+color-mode@3.5.2_magicast@0.5.1/node_modules/@nuxtjs/color-mode/dist/runtime/plugin.client.js")> &
  InjectionType<typeof import("../../node_modules/.pnpm/nuxt@3.20.1_@parcel+watcher@2.5.1_@types+node@24.10.1_@vue+compiler-sfc@3.5.24_db0@0.3._b5c6af8f109483f88e7516349693bf5a/node_modules/nuxt/dist/app/plugins/warn.dev.server.js")> &
  InjectionType<typeof import("../../node_modules/.pnpm/nuxt@3.20.1_@parcel+watcher@2.5.1_@types+node@24.10.1_@vue+compiler-sfc@3.5.24_db0@0.3._b5c6af8f109483f88e7516349693bf5a/node_modules/nuxt/dist/app/plugins/check-if-layout-used.js")> &
  InjectionType<typeof import("../../node_modules/.pnpm/nuxt@3.20.1_@parcel+watcher@2.5.1_@types+node@24.10.1_@vue+compiler-sfc@3.5.24_db0@0.3._b5c6af8f109483f88e7516349693bf5a/node_modules/nuxt/dist/pages/runtime/plugins/prerender.server.js")> &
  InjectionType<typeof import("../../node_modules/.pnpm/nuxt-seo-utils@7.0.18_h3@1.15.4_magicast@0.5.1_rollup@4.53.2_vue@3.5.24_typescript@5.9.3_/node_modules/nuxt-seo-utils/dist/runtime/app/plugins/1.absoluteImageUrls.server.js")> &
  InjectionType<typeof import("../../node_modules/.pnpm/nuxt-seo-utils@7.0.18_h3@1.15.4_magicast@0.5.1_rollup@4.53.2_vue@3.5.24_typescript@5.9.3_/node_modules/nuxt-seo-utils/dist/runtime/app/plugins/0.routeRules.js")> &
  InjectionType<typeof import("../../node_modules/.pnpm/nuxt-seo-utils@7.0.18_h3@1.15.4_magicast@0.5.1_rollup@4.53.2_vue@3.5.24_typescript@5.9.3_/node_modules/nuxt-seo-utils/dist/runtime/app/plugins/defaults.js")>

declare module '#app' {
  interface NuxtApp extends NuxtAppInjections { }

  interface NuxtAppLiterals {
    pluginName: 'nuxt:revive-payload:client' | 'nuxt-site-config:init' | 'nuxt:head' | 'nuxt:router' | 'nuxt:browser-devtools-timing' | 'nuxt:revive-payload:server' | 'nuxt:chunk-reload' | 'nuxt-seo:fallback-titles' | 'nuxt-schema-org:defaults' | 'nuxt-schema-org:init' | 'nuxt:global-components' | 'nuxt:prefetch' | 'nuxt:checkIfPageUnused' | 'nuxt:checkIfLayoutUsed' | 'nuxt-seo:defaults'
  }
}

declare module 'vue' {
  interface ComponentCustomProperties extends NuxtAppInjections { }
}

export { }
