// Generated by nuxt-robots
declare module 'nitropack' {
  interface PrerenderRoute {
    _sitemap?: import('../../node_modules/.pnpm/@nuxtjs+sitemap@7.4.7_h3@1.15.4_magicast@0.5.1_vite@7.2.2_@types+node@24.10.1_jiti@2.6._26ae4d3e07f5eabb14457504a2a7d732/node_modules/@nuxtjs/sitemap/dist/runtime/types').SitemapUrl
  }
  interface NitroRouteRules {
    index?: boolean
    sitemap?: import('../../node_modules/.pnpm/@nuxtjs+sitemap@7.4.7_h3@1.15.4_magicast@0.5.1_vite@7.2.2_@types+node@24.10.1_jiti@2.6._26ae4d3e07f5eabb14457504a2a7d732/node_modules/@nuxtjs/sitemap/dist/runtime/types').SitemapItemDefaults
  }
  interface NitroRouteConfig {
    index?: boolean
    sitemap?: import('../../node_modules/.pnpm/@nuxtjs+sitemap@7.4.7_h3@1.15.4_magicast@0.5.1_vite@7.2.2_@types+node@24.10.1_jiti@2.6._26ae4d3e07f5eabb14457504a2a7d732/node_modules/@nuxtjs/sitemap/dist/runtime/types').SitemapItemDefaults
  }
  interface NitroRuntimeHooks {
    'sitemap:index-resolved': (ctx: import('../../node_modules/.pnpm/@nuxtjs+sitemap@7.4.7_h3@1.15.4_magicast@0.5.1_vite@7.2.2_@types+node@24.10.1_jiti@2.6._26ae4d3e07f5eabb14457504a2a7d732/node_modules/@nuxtjs/sitemap/dist/runtime/types').SitemapIndexRenderCtx) => void | Promise<void>
    'sitemap:input': (ctx: import('../../node_modules/.pnpm/@nuxtjs+sitemap@7.4.7_h3@1.15.4_magicast@0.5.1_vite@7.2.2_@types+node@24.10.1_jiti@2.6._26ae4d3e07f5eabb14457504a2a7d732/node_modules/@nuxtjs/sitemap/dist/runtime/types').SitemapInputCtx) => void | Promise<void>
    'sitemap:resolved': (ctx: import('../../node_modules/.pnpm/@nuxtjs+sitemap@7.4.7_h3@1.15.4_magicast@0.5.1_vite@7.2.2_@types+node@24.10.1_jiti@2.6._26ae4d3e07f5eabb14457504a2a7d732/node_modules/@nuxtjs/sitemap/dist/runtime/types').SitemapRenderCtx) => void | Promise<void>
    'sitemap:output': (ctx: import('../../node_modules/.pnpm/@nuxtjs+sitemap@7.4.7_h3@1.15.4_magicast@0.5.1_vite@7.2.2_@types+node@24.10.1_jiti@2.6._26ae4d3e07f5eabb14457504a2a7d732/node_modules/@nuxtjs/sitemap/dist/runtime/types').SitemapOutputHookCtx) => void | Promise<void>
    'sitemap:sources': (ctx: import('../../node_modules/.pnpm/@nuxtjs+sitemap@7.4.7_h3@1.15.4_magicast@0.5.1_vite@7.2.2_@types+node@24.10.1_jiti@2.6._26ae4d3e07f5eabb14457504a2a7d732/node_modules/@nuxtjs/sitemap/dist/runtime/types').SitemapSourcesHookCtx) => void | Promise<void>
  }
}
declare module 'nitropack/types' {
  interface PrerenderRoute {
    _sitemap?: import('../../node_modules/.pnpm/@nuxtjs+sitemap@7.4.7_h3@1.15.4_magicast@0.5.1_vite@7.2.2_@types+node@24.10.1_jiti@2.6._26ae4d3e07f5eabb14457504a2a7d732/node_modules/@nuxtjs/sitemap/dist/runtime/types').SitemapUrl
  }
  interface NitroRouteRules {
    index?: boolean
    sitemap?: import('../../node_modules/.pnpm/@nuxtjs+sitemap@7.4.7_h3@1.15.4_magicast@0.5.1_vite@7.2.2_@types+node@24.10.1_jiti@2.6._26ae4d3e07f5eabb14457504a2a7d732/node_modules/@nuxtjs/sitemap/dist/runtime/types').SitemapItemDefaults
  }
  interface NitroRouteConfig {
    index?: boolean
    sitemap?: import('../../node_modules/.pnpm/@nuxtjs+sitemap@7.4.7_h3@1.15.4_magicast@0.5.1_vite@7.2.2_@types+node@24.10.1_jiti@2.6._26ae4d3e07f5eabb14457504a2a7d732/node_modules/@nuxtjs/sitemap/dist/runtime/types').SitemapItemDefaults
  }
  interface NitroRuntimeHooks {
    'sitemap:index-resolved': (ctx: import('../../node_modules/.pnpm/@nuxtjs+sitemap@7.4.7_h3@1.15.4_magicast@0.5.1_vite@7.2.2_@types+node@24.10.1_jiti@2.6._26ae4d3e07f5eabb14457504a2a7d732/node_modules/@nuxtjs/sitemap/dist/runtime/types').SitemapIndexRenderCtx) => void | Promise<void>
    'sitemap:input': (ctx: import('../../node_modules/.pnpm/@nuxtjs+sitemap@7.4.7_h3@1.15.4_magicast@0.5.1_vite@7.2.2_@types+node@24.10.1_jiti@2.6._26ae4d3e07f5eabb14457504a2a7d732/node_modules/@nuxtjs/sitemap/dist/runtime/types').SitemapInputCtx) => void | Promise<void>
    'sitemap:resolved': (ctx: import('../../node_modules/.pnpm/@nuxtjs+sitemap@7.4.7_h3@1.15.4_magicast@0.5.1_vite@7.2.2_@types+node@24.10.1_jiti@2.6._26ae4d3e07f5eabb14457504a2a7d732/node_modules/@nuxtjs/sitemap/dist/runtime/types').SitemapRenderCtx) => void | Promise<void>
    'sitemap:output': (ctx: import('../../node_modules/.pnpm/@nuxtjs+sitemap@7.4.7_h3@1.15.4_magicast@0.5.1_vite@7.2.2_@types+node@24.10.1_jiti@2.6._26ae4d3e07f5eabb14457504a2a7d732/node_modules/@nuxtjs/sitemap/dist/runtime/types').SitemapOutputHookCtx) => void | Promise<void>
    'sitemap:sources': (ctx: import('../../node_modules/.pnpm/@nuxtjs+sitemap@7.4.7_h3@1.15.4_magicast@0.5.1_vite@7.2.2_@types+node@24.10.1_jiti@2.6._26ae4d3e07f5eabb14457504a2a7d732/node_modules/@nuxtjs/sitemap/dist/runtime/types').SitemapSourcesHookCtx) => void | Promise<void>
  }
}
declare module 'vue-router' {
    interface RouteMeta {
        sitemap?: import('../../node_modules/.pnpm/@nuxtjs+sitemap@7.4.7_h3@1.15.4_magicast@0.5.1_vite@7.2.2_@types+node@24.10.1_jiti@2.6._26ae4d3e07f5eabb14457504a2a7d732/node_modules/@nuxtjs/sitemap/dist/runtime/types').SitemapItemDefaults
    }
}

export {}
