// Generated by nuxt-seo-utils

import type { RobotsContext } from '#robots/types'

declare module 'nitropack/types' {
  interface NitroRouteRules {
     seoMeta?: import('../../node_modules/.pnpm/nuxt-seo-utils@7.0.18_h3@1.15.4_magicast@0.5.1_rollup@4.53.2_vue@3.5.24_typescript@5.9.3_/node_modules/nuxt-seo-utils/dist/runtime/types').MetaFlatSerializable
     head?: import('../../node_modules/.pnpm/nuxt-seo-utils@7.0.18_h3@1.15.4_magicast@0.5.1_rollup@4.53.2_vue@3.5.24_typescript@5.9.3_/node_modules/nuxt-seo-utils/dist/runtime/types').Head
  }
  interface NitroRouteConfig {
    seoMeta?: import('../../node_modules/.pnpm/nuxt-seo-utils@7.0.18_h3@1.15.4_magicast@0.5.1_rollup@4.53.2_vue@3.5.24_typescript@5.9.3_/node_modules/nuxt-seo-utils/dist/runtime/types').MetaFlatSerializable
    head?: import('../../node_modules/.pnpm/nuxt-seo-utils@7.0.18_h3@1.15.4_magicast@0.5.1_rollup@4.53.2_vue@3.5.24_typescript@5.9.3_/node_modules/nuxt-seo-utils/dist/runtime/types').Head
  }
}

declare module 'nitropack' {
  interface NitroRouteRules {
     seoMeta?: import('../../node_modules/.pnpm/nuxt-seo-utils@7.0.18_h3@1.15.4_magicast@0.5.1_rollup@4.53.2_vue@3.5.24_typescript@5.9.3_/node_modules/nuxt-seo-utils/dist/runtime/types').MetaFlatSerializable
     head?: import('../../node_modules/.pnpm/nuxt-seo-utils@7.0.18_h3@1.15.4_magicast@0.5.1_rollup@4.53.2_vue@3.5.24_typescript@5.9.3_/node_modules/nuxt-seo-utils/dist/runtime/types').Head
  }
  interface NitroRouteConfig {
    seoMeta?: import('../../node_modules/.pnpm/nuxt-seo-utils@7.0.18_h3@1.15.4_magicast@0.5.1_rollup@4.53.2_vue@3.5.24_typescript@5.9.3_/node_modules/nuxt-seo-utils/dist/runtime/types').MetaFlatSerializable
    head?: import('../../node_modules/.pnpm/nuxt-seo-utils@7.0.18_h3@1.15.4_magicast@0.5.1_rollup@4.53.2_vue@3.5.24_typescript@5.9.3_/node_modules/nuxt-seo-utils/dist/runtime/types').Head
  }
}


declare module '@nuxt/schema' {
  interface AppHeadMetaObject { seoMeta?: import('../../node_modules/.pnpm/nuxt-seo-utils@7.0.18_h3@1.15.4_magicast@0.5.1_rollup@4.53.2_vue@3.5.24_typescript@5.9.3_/node_modules/nuxt-seo-utils/dist/runtime/types').MetaFlatSerializable }
}

declare module 'nuxt/schema' {
  interface AppHeadMetaObject { seoMeta?: import('../../node_modules/.pnpm/nuxt-seo-utils@7.0.18_h3@1.15.4_magicast@0.5.1_rollup@4.53.2_vue@3.5.24_typescript@5.9.3_/node_modules/nuxt-seo-utils/dist/runtime/types').MetaFlatSerializable }
}

export {}
